### ISSUE TITLE
NuGet package?

### ISSUE THREAD

**Issue by GunsRoseSS** [creativesuspects/SvgIconPropertyEditor#1]
Hi @creativesuspects,

I'm currently updating an Umbraco 8 project to v10, where one of the packages used was the [FontAwesomePropertyEditor](https://github.com/mjbarlow/Font-Awesome-Links-Property-Editor) package by mjbarlow. In his readme file he mentioned this package as an alternative.

I've also read your [issue on the archived project](https://github.com/mjbarlow/Font-Awesome-Links-Property-Editor/issues/10), but I can't seem to find a public NuGet package of the new project. Are there any plans to make this package public?

**Comment by creativesuspects** [comment]
I currently don't have time to turn this into a public NuGet package. But feel free to fork the repo and turn it into a NuGet package. Or contact me on Skype (...) and I'd be happy to share my self-hosted NuGet package with you. No guarantees of course and I don't actively work on the package unless there's a serious bug. But I'm using the package on multipe production sites without any issues.

Please note that my version of the package is not compatible with the v8 version due to some model changes. So you can't just swap out the package to make it work.

**Comment by GunsRoseSS** [comment]
Thanks for the quick response.
For now I'll just put your code in my project and tinker with it until it works.

I'll close this issue for now. Thanks again!
